---
# Template configuration files for zuul

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ zuul_templates_copy }}"
  when: zuul_copy_templates
